In [1]:
import pandas as pd

In [2]:
raw_data = [
    {"patient_id": "001", "age": "72", "biomarker": "amyloid", "score": "14.2", "diagnosis": "alzheimers"},
    {"patient_id": "002", "age": "68", "biomarker": "tau", "score": " 9.8 ", "diagnosis": "Alzheimer's"},
    {"patient_id": "003", "age": "unknown", "biomarker": "Amyloid", "score": "15.1", "diagnosis": "control"},
    {"patient_id": "004", "age": "75", "biomarker": "tau", "score": "not available", "diagnosis": "alz"},
    {"patient_id": "005", "age": "70", "biomarker": "amyloid ", "score": "13.7", "diagnosis": "Control"},
    {"patient_id": "006", "age": None, "biomarker": "Tau", "score": "11.4", "diagnosis": "AD"},
]

In [3]:
df_raw = pd.DataFrame(raw_data)

In [5]:
df = df_raw.copy()
df

  patient_id      age biomarker          score    diagnosis
0        001       72   amyloid           14.2   alzheimers
1        002       68       tau           9.8   Alzheimer's
2        003  unknown   Amyloid           15.1      control
3        004       75       tau  not available          alz
4        005       70  amyloid            13.7      Control
5        006      NaN       Tau           11.4           AD

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  6 non-null      str
 1   age         5 non-null      str
 2   biomarker   6 non-null      str
 3   score       6 non-null      str
 4   diagnosis   6 non-null      str
dtypes: str(5)
memory usage: 372.0 bytes

In [13]:
df["biomarker"] = df["biomarker"].str.strip().str.lower()
df["diagnosis"] = df["diagnosis"].str.strip().str.lower()

In [14]:
diagnosis_map = {
    "alzheimers": "alzheimers",
    "alzheimer's": "alzheimers",
    "alz": "alzheimers",
    "ad": "alzheimers",
    "control": "control"
}

df["diagnosis"] = df["diagnosis"].replace(diagnosis_map)
df

  patient_id      age biomarker          score   diagnosis
0        001       72   amyloid           14.2  alzheimers
1        002       68       tau           9.8   alzheimers
2        003  unknown   amyloid           15.1     control
3        004       75       tau  not available  alzheimers
4        005       70   amyloid           13.7     control
5        006      NaN       tau           11.4  alzheimers

In [15]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["score"] = pd.to_numeric(df["score"], errors="coerce")

df

  patient_id   age biomarker  score   diagnosis
0        001  72.0   amyloid   14.2  alzheimers
1        002  68.0       tau    9.8  alzheimers
2        003   NaN   amyloid   15.1     control
3        004  75.0       tau    NaN  alzheimers
4        005  70.0   amyloid   13.7     control
5        006   NaN       tau   11.4  alzheimers

In [16]:
df.isna().sum()

patient_id    0
age           2
biomarker     0
score         1
diagnosis     0
dtype: int64

In [17]:
df_clean = df.dropna(subset=["age", "score"]).copy()
df_clean

  patient_id   age biomarker  score   diagnosis
0        001  72.0   amyloid   14.2  alzheimers
1        002  68.0       tau    9.8  alzheimers
4        005  70.0   amyloid   13.7     control

In [18]:
df_clean["age"] = df_clean["age"].astype(int)

In [19]:
df_clean["score"] = df_clean["score"].astype(float)

In [22]:
df_clean

  patient_id  age biomarker  score   diagnosis
0        001   72   amyloid   14.2  alzheimers
1        002   68       tau    9.8  alzheimers
4        005   70   amyloid   13.7     control

In [23]:
df_clean.groupby("diagnosis")["score"].mean()

diagnosis
alzheimers    12.0
control       13.7
Name: score, dtype: float64

In [24]:
df_clean.groupby("biomarker")["score"].mean()

biomarker
amyloid    13.95
tau         9.80
Name: score, dtype: float64

In [25]:
df_clean["diagnosis"].value_counts()

diagnosis
alzheimers    2
control       1
Name: count, dtype: int64

In [26]:
df_clean.to_csv("alzheimers_cleaned.csv", index=False)